import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import LinkedInProvider from "../context/linkedInContext";
import {Toaster} from "react-hot-toast"

export const metadata: Metadata = {
  title: {
    default: "LinkedIn",
    template: " LinkedIn | %s  "
  } ,
  description: "Generated by create next app",
   icons: {
    icon: "/favicon.svg", // path inside /public
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LinkedInProvider>
          {/* <Header /> */}
          
          <div className="md:px-10 px-2 py-1 md:py-6 w-full md:pt-[80px] pt-[80px]  h-screen overflow-y-scroll overflow-hidden my-scroll-container">
            {children}
          </div>
          <Toaster />
        </LinkedInProvider>
      </body>
    </html>
  );
}
